import argparse
import logging
from pathlib import Path

from dotenv import load_dotenv

from japan_stock_youtube_shorts.config import RuntimeConfig
from japan_stock_youtube_shorts.notion.health import healthcheck as notion_healthcheck
from japan_stock_youtube_shorts.openai.health import healthcheck as openai_healthcheck
from japan_stock_youtube_shorts.pipelines.generate_chart import create_price_chart
from japan_stock_youtube_shorts.pipelines.generate_script import generate_script_for_ticker
from japan_stock_youtube_shorts.pipelines.generate_video import assemble_video


def configure_logging(level: str) -> None:
    logging.basicConfig(
        level=getattr(logging, level, logging.INFO),
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="YouTube Shorts pipeline for Japanese stocks.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    parser.add_argument("--dry-run", action="store_true", help="Skip external API calls and writes.")
    parser.add_argument("--run-id", help="Provide a run identifier (otherwise autogenerated).")
    parser.add_argument("--log-level", default="INFO", help="Logging level (INFO, WARN, ERROR, DEBUG).")

    script_parser = subparsers.add_parser("script", help="Generate a narration script.")
    script_parser.add_argument("--ticker", required=True, help="Ticker symbol (e.g. 7203.T).")
    script_parser.add_argument("--company", required=True, help="Company name.")
    script_parser.add_argument("--period", default="1mo", help="yfinance period (default: 1mo).")
    script_parser.add_argument("--notion-page", help="Optional Notion page ID to update.")
    script_parser.add_argument("--output", type=Path, help="Path to save the generated script.")

    chart_parser = subparsers.add_parser("chart", help="Create a price chart image.")
    chart_parser.add_argument("--ticker", required=True, help="Ticker symbol.")
    chart_parser.add_argument("--period", default="1mo", help="yfinance period.")
    chart_parser.add_argument("--output", type=Path, help="Where to write the chart PNG.")

    video_parser = subparsers.add_parser("video", help="Combine audio + image into a clip.")
    video_parser.add_argument("--image", type=Path, required=True, help="Path to an image to show.")
    video_parser.add_argument("--audio", type=Path, required=True, help="Narration audio file.")
    video_parser.add_argument("--output", type=Path, help="Target MP4 path.")
    video_parser.add_argument("--fps", type=int, default=30, help="Frames per second.")

    subparsers.add_parser("healthcheck", help="Run OpenAI and Notion connectivity checks.")

    return parser.parse_args()


def main() -> None:
    args = parse_args()
    load_dotenv()
    runtime = RuntimeConfig.from_env(run_id=args.run_id, log_level=args.log_level, dry_run=args.dry_run)
    configure_logging(runtime.log_level)
    logging.getLogger(__name__).info("Run started (run_id=%s, dry_run=%s)", runtime.run_id, runtime.dry_run)

    if args.command == "script":
        script = generate_script_for_ticker(
            args.ticker,
            args.company,
            period=args.period,
            notion_page_id=args.notion_page,
            output_path=args.output,
            runtime_config=runtime,
        )
        print(script)

    elif args.command == "chart":
        output = create_price_chart(args.ticker, period=args.period, output_path=args.output, runtime_config=runtime)
        print(f"Chart saved to {output}")

    elif args.command == "video":
        output = assemble_video(args.image, args.audio, output_path=args.output, fps=args.fps, runtime_config=runtime)
        print(f"Video saved to {output}")

    elif args.command == "healthcheck":
        openai_healthcheck()
        notion_healthcheck()
        print("Healthcheck completed.")

    logging.getLogger(__name__).info("Run finished (run_id=%s)", runtime.run_id)


if __name__ == "__main__":
    main()
